
GET http://localhost:3001/users

###
POST http://localhost:3001/users
Content-Type: application/json





###
GET http://localhost:3001/items

###
PUT http://localhost:3001/items/6740f3758f6b40118c3dabff
    Content-Type: application/json

    {
        "name": "No name"
    }